<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="its.php" method="post">
        <label >Enter your name</label>
        <input type="text" name="nm">
        <hr>
        <label>Enter your Number</label>
        <input type="text" name="mb" id="num">
        <hr>
        <input type="submit" value="submit">

    </form>
</body>
</html>